intro/intro/urls.py
from django.contrib import admin
from django.urls import path, include

from intro.views import hello, welcome
from home.views import hi, adam, ewa, welcome


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('witaj/', welcome),
    path('hi/', hi),
    path('adam/', adam),
    path('ewa/', ewa),
    path('welcome/<str:name>/', welcome),

    path('next/', include('next.urls')),
    path('hello/', include('hello_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form0/', include('form_app0.urls')),
    path('form1/', include('form_app1.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('task/', include('task_app.urls')),
    path('relations/', include('relations.urls')),
    path('form5/', include('form_app5.urls')),
    path('view/', include('view_app.urls')),
    path('cookie/', include('cookies_app.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

intro/next/urls.py
from django.urls import path

from next import views


urlpatterns = [
    path('hello/', views.hello),
    path('hello2/', views.hello2),
    path('isitnewyear/', views.is_it_new_year),
    path('fruits/', views.fruits),

    path('<str:name>/', views.name_view),
]

intro/task_app/urls.py
from django.urls import path

from task_app import views

app_name = 'task_app'

urlpatterns = [
    path('create/', views.task_create, name='task_create'),  # C z CRUD

    path('list/', views.task_list, name='task_list'),  # R z CRUD (widok listy)
    path('<int:id>/', views.task_detail, name='task_detail'),  # R z CRUD (widok szczegółu)

    path('<int:id>/update/', views.task_update, name='task_update'),  # U z CRUD

    path('<int:id>/delete/', views.task_delete, name='task_delete'),  # D z CRUD
]

intro/task_app/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=64)
    added = models.DateTimeField(auto_now_add=True)

intro/task_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from task_app.models import Task


# Widok tworzenia (Create - C z CRUD)
def task_create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        if title:
            Task.objects.create(name=title)

        return redirect('task_app:task_list')

    return render(
        request,
        'task_app/task_create.html'
    )


# Widok listy (Read - R z CRUD)
def task_list(request):
    tasks = Task.objects.all()

    return render(
        request,
        'task_app/task_list.html',
        context={
            'tasks': tasks,
        }
    )


# Widok detalu (Read - R z CRUD)
def task_detail(request, id):
    task = get_object_or_404(Task, id=id)

    return render(
        request,
        'task_app/task_detail.html',
        context={
            'task': task,
        }
    )


# Widok modyfikacji (Update - U z CRUD)
def task_update(request, id):
    task = get_object_or_404(Task, id=id)

    if request.method == "POST":
        title = request.POST.get('title')

        if title:
            task.name = title
            task.save()

        return redirect('task_app:task_list')

    return render(
        request,
        'task_app/task_update.html',
        context={
            'task': task
        }
    )


# Widok usuwanie (Delete - D z CRUD)
def task_delete(request, id):
    task = get_object_or_404(Task, id=id)

    if request.method == "POST":
        task.delete()

        return redirect('task_app:task_list')

    return render(
        request,
        'task_app/task_confirm_delete.html',
        context={
            'task': task,
        }
    )

intro/task_app/templates/task_app/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body class="container" style="margin-top:2%;">
  {% block body %}{% endblock %}
</body>
</html>

intro/task_app/templates/task_app/task_confirm_delete.html
{% extends "task_app/layout.html" %}

{% block body %}
    <h2>Usuwanie zadania o numerze {{ task.id }}</h2>
    <form method="POST">
        {% csrf_token %}
        <p>Czy na pewno chcesz usunąć zadanie {{ task.name }}?</p>
        <input type="submit" class="btn btn-danger" value="Potwierdź">
    </form>
    <a href="{% url 'task_app:task_list' %}"><button class='btn btn-info'style="margin-top:5px;">Anuluj</button></a>
{% endblock %}

intro/task_app/templates/task_app/task_create.html
{% extends "task_app/layout.html" %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Tytuł zadania" required>
        <input type="submit" class="btn btn-primary" value="Zapisz zadanie">
    </form>

    <a href="{% url 'task_app:task_list' %}"><button class="btn btn-info" style="margin-top:5px;">Lista zadań</button></a>
{% endblock %}

intro/task_app/templates/task_app/task_detail.html
{% extends "task_app/layout.html" %}

{% block body %}
  <h2>Zadanie o numerze {{ task.id }}</h2>
  <p><b>Nazwa:</b> {{ task.name }}</p>
  <p><b>Dodano:</b> {{task.added }}</p>

  <a href="{% url 'task_app:task_list' %}"><button>Lista zadań</button></a>
{% endblock %}

intro/task_app/templates/task_app/task_list.html
{% extends "task_app/layout.html" %}

{% block title %}
Lista zadań
{% endblock %}

{% block body %}
    <h2>Lista zadań:</h2>
    <a href="{% url 'task_app:task_create' %}"><button class="btn btn-primary" style="padding:5px;">Dodaj zadanie</button></a>
    <ul>
        {% for task in tasks %}
            <li style="margin:1%;">
                <a href="{% url 'task_app:task_detail' task.id %}">{{ task.name }}</a>
                <a href="{% url 'task_app:task_update' task.id %}"><button class="btn btn-primary">Modyfikuj</button></a>
                <a href="{% url 'task_app:task_delete' task.id %}"><button class="btn btn-danger">Usuń</button></a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

intro/task_app/templates/task_app/task_update.html
{% extends "task_app/layout.html" %}

{% block body %}
    <h2>Modyfikacja zadania o numerze {{ task.id }}</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="title" value="{{ task.name }}" placeholder="Tytuł zadania" required>
        <input type="submit" class="btn btn-primary" value="Zmodyfikuj zadanie">
    </form>
    <a href="{% url 'task_app:task_list' %}"><button class="btn btn-info" style="margin-top:5px;">Lista zadań</button></a>
{% endblock %}