intro/form_app0/urls.py
from django.urls import path

from form_app0 import views

app_name = 'form_app0'

urlpatterns = [
    path('', views.create_task, name='create_task'),
    path('task-list/', views.task_list, name='task_list'),
]

intro/intro/urls.py
from django.contrib import admin
from django.urls import path, include

from intro.views import hello, welcome
from home.views import hi, adam, ewa, welcome


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('witaj/', welcome),
    path('hi/', hi),
    path('adam/', adam),
    path('ewa/', ewa),
    path('welcome/<str:name>/', welcome),

    path('next/', include('next.urls')),
    path('hello/', include('hello_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form0/', include('form_app0.urls')),
    path('form1/', include('form_app1.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('task/', include('task_app.urls')),
    path('relations/', include('relations.urls')),
    path('form5/', include('form_app5.urls')),
    path('view/', include('view_app.urls')),
    path('cookie/', include('cookies_app.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

intro/next/urls.py
from django.urls import path

from next import views


urlpatterns = [
    path('hello/', views.hello),
    path('hello2/', views.hello2),
    path('isitnewyear/', views.is_it_new_year),
    path('fruits/', views.fruits),

    path('<str:name>/', views.name_view),
]

intro/form_app0/views.py
from django.shortcuts import render

TASKS = []


def create_task(request):
    return render(
        request,
        'form_app0/create_task.html'
    )


def task_list(request):
    task = request.GET.get('task')
    if task:
        TASKS.append(task)

    return render(
        request,
        'form_app0/task_list.html',
        context={
            'tasks': TASKS
        }
    )

intro/form_app0/templates/form_app0/create_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'form_app0:task_list' %}">
        <input type="text" name="task" placeholder="zadanie">
        <input type="submit" value="Zarejestruj">
    </form>
</body>
</html>

intro/form_app0/templates/form_app0/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h2>Lista zadań:</h2>
    <ol>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ol>
</body>
</html>